import {
  BadgeCheck,
  Bot,
  Box,
  BrainCircuit,
  CircleHelp,
  Download,
  FileText,
  Image,
  Layers3,
  LayoutGrid,
  ListChecks,
  MessagesSquare,
  MousePointerClick,
  Orbit,
  PanelBottom,
  PanelTop,
  PanelTopOpen,
  PenTool,
  Quote,
  Rocket,
  ShieldCheck,
  Sparkles,
  TerminalSquare,
  Workflow,
} from 'lucide-react';

const iconRegistry = {
  BadgeCheck,
  Bot,
  Box,
  BrainCircuit,
  CircleHelp,
  Download,
  FileText,
  Image,
  Layers3,
  LayoutGrid,
  ListChecks,
  MessagesSquare,
  MousePointerClick,
  Orbit,
  PanelBottom,
  PanelTop,
  PanelTopOpen,
  PenTool,
  Quote,
  Rocket,
  ShieldCheck,
  Sparkles,
  TerminalSquare,
  Workflow,
};

export function Icon({ name = 'Sparkles', size = 20, strokeWidth = 1.8, ...props }) {
  const Component = iconRegistry[name] || Sparkles;
  return <Component aria-hidden="true" size={size} strokeWidth={strokeWidth} {...props} />;
}
